### ISSUE TITLE
Where is the dataset?

### ISSUE THREAD

**Issue by detectRecog** [vranlee/TFMFT#1]
Hello, I wonder when will the dataset be released?

**Comment by vranlee** [comment]
Hello, it can be found in this repo. [[GitHub|MFT_DATASETS]](https://github.com/vranlee/MFT_DATASETS/)
We have invited collaborators and are preparing a large benchmark. It will contain the full relevant data mentioned above and will be released around 2025.
We hope this will be of some help to you!
